name: ValkyaClaims
main: fr.volax.valkyaclaims.ValkyaClaims
version: 1.0.04
depend: [Vault, Factions]
description: Valkya Claims for Valkya about AP and Faction Houses
commands:
  ap:
    description: "Commande des AP's"
