name: ValkyaClaims
main: fr.volax.valkyaclaims.ValkyaClaims
version: 1.0.03
depend: [Vault, Factions]
description: Valkya Claims for Valkya about AP and Faction Houses
commands:
  claims:
    description: "Commande des claims"